Add loaders
nycJSorg/30-seconds-of-angular pull request #11
Opened 2019-03-09 11:33 UTC by Jamaks

2019-03-10 16:03 UTC, kirjs commented on snippets/loader.md
> +# Bonus
Remove

2019-03-10 16:03 UTC, kirjs commented on snippets/loader.md
> +  <div *ngIf="model withLoading">
Break up into 2 snippets

2019-03-11 04:44 UTC, thekiba commented on snippets/loader.md
> +  selector: '[ngIfWithLoading]',
It's a bad practice when structural directive doesn't take values in Input.

2019-03-22 17:05 UTC, kirjs commented
Can we make the content fit into 25 line please?

2019-04-21 19:53 UTC, kirjs commented on snippets/loader.md
> +  <button (click)="model = !model">Toggle</button>
model -> should this look like a boolean var? e.x. isXxxx

2019-04-21 19:56 UTC, kirjs requested changes

2019-04-21 19:56 UTC, kirjs commented on snippets/loader.md
> +@Component({
Can we turn this in a simple structural directive with 1 example? too much stuff otherwise.

2019-05-21 03:29 UTC, NothingEverHappens commented
I'm trying to recall what was the latest decision on this one. 
I think the plan was to drop it, but feel free to reopen if I am mistaken

2019-05-21 03:30 UTC, closed without merging