Add - new snippet: Preseving whitespaces
nycJSorg/30-seconds-of-angular pull request #167
Opened 2019-06-13 23:26 UTC by NothingEverHappens

Here is a new snippet. Hope you like it :)

2019-06-13 23:27 UTC, NothingEverHappens commented
Fixes #54

2019-06-14 06:42 UTC, fetis requested changes

2019-06-14 06:42 UTC, fetis commented on snippets/preseving-whitespaces.md
> + <h1> Now look at me, I'm cute!! </h1>
I think 1 time is enough :)

2019-06-14 06:42 UTC, fetis commented on snippets/preseving-whitespaces.md
> +export class AppComponent {}
demo?

2019-06-26 18:52 UTC, fetis approved these changes

2019-06-26 18:53 UTC, merged