Add tabs component
nycJSorg/30-seconds-of-angular pull request #29
Opened 2019-03-13 09:15 UTC by Jamaks

review in #6

2019-03-15 15:14 UTC, thekiba requested changes

2019-03-15 15:14 UTC, thekiba commented on snippets/tabs-component.md
> +  import { Component, Input, AfterContentInit, ContentChildren, QueryList } from '@angular/core';
```suggestion
import { Component, Input, AfterContentInit, ContentChildren, QueryList } from '@angular/core';
```

2019-03-15 15:14 UTC, thekiba commented on snippets/tabs-component.md
> +  `,
need add extra indent for template

2019-03-15 15:14 UTC, thekiba commented on snippets/tabs-component.md
> +     tab.active = true;
```suggestion
    tab.active = true;
```

2019-03-15 15:14 UTC, thekiba commented on snippets/tabs-component.md
> + </app-tabs>
Need add description and wrap code

2019-03-22 17:13 UTC, NothingEverHappens commented
Closing after talking to @irustm, it's cool, but would be really hard to fit the format

2019-03-23 11:55 UTC, closed without merging