Added di composition snippet
nycJSorg/30-seconds-of-angular pull request #9
Opened 2019-03-09 08:38 UTC by thekiba

Нужен перевод

2019-03-10 16:32 UTC, kirjs requested changes

2019-03-10 16:32 UTC, kirjs commented on snippets/di-composition.md
> +  @HostListener('click') onClick() {
This is a very elaborate example, also hostbinding and hostlistener each deserve their own snippet.

2019-03-13 09:05 UTC, fetis commented
this described in Angular doc https://angular.io/guide/hierarchical-dependency-injection#component-level-injectors
do we need to have this as a snippet?

2019-03-13 09:08 UTC, thekiba commented
@fetis yep, because this is not a popular way to using angular di

2019-03-13 19:24 UTC, fetis requested changes

2019-03-13 19:24 UTC, fetis commented on snippets/di-composition.md
> +
```suggestion
https://angular.io/guide/hierarchical-dependency-injection#component-level-injectors

```

2019-03-13 19:34 UTC, fetis commented
btw, "DI composition" says nothing for me. Maybe re-phrase it to more clear name?

2019-03-22 17:04 UTC, kirjs commented
Can we have a shorter example please

2019-03-25 19:20 UTC, fetis requested changes

2019-03-25 19:20 UTC, fetis commented on snippets/component-level-providers.md
> +@Component({
```suggestion
@Directive({
```

2019-03-25 19:20 UTC, fetis commented on snippets/component-level-providers.md
> +  unlink(item: ItemComponent) {
```suggestion

  unlink(item: ItemComponent) {
```

2019-03-25 19:20 UTC, fetis commented on snippets/component-level-providers.md
> +  links: Set<ItemComponent> = new Set();
just a better isolation
```suggestion
  private links: Set<ItemComponent> = new Set();
```

2019-03-27 06:51 UTC, fetis approved these changes

2019-04-21 19:57 UTC, kirjs approved these changes

2019-04-21 19:57 UTC, merged